services:
  - type: web
    name: tweetscheduler-pro
    runtime: node
    plan: starter
    region: oregon
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: tweetscheduler-api
    runtime: node
    plan: starter
    region: oregon
    branch: main
    buildCommand: npm ci && npm run prisma:generate
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: DATABASE_URL
        sync: false
      - key: ENCRYPTION_KEY
        sync: false

  - type: worker
    name: tweet-scheduler-worker
    runtime: node
    plan: starter
    branch: main
    buildCommand: npm ci && npm run prisma:generate
    startCommand: npm run worker
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: DATABASE_URL
        sync: false


databases:
  # If you need a PostgreSQL database for Supabase self-hosting
  # - name: tweetscheduler-db
  #   databaseName: tweetscheduler
  #   user: tweetscheduler_user
  #   plan: starter

# Optional: Background services for scheduled tasks
# - type: worker
#   name: tweet-scheduler-worker
#   runtime: node
#   plan: starter
#   buildCommand: npm ci
#   startCommand: node scripts/scheduler-worker.js
#   envVars:
#     - key: NODE_VERSION
#       value: "18"
#     - key: SUPABASE_URL
#       sync: false
#     - key: SUPABASE_SERVICE_ROLE_KEY
#       sync: false

